ALTER TABLE "valores_uf_utm" ADD COLUMN "afpCapital"   DECIMAL(6,4) NOT NULL DEFAULT 0.1144;
ALTER TABLE "valores_uf_utm" ADD COLUMN "afpCuprum"    DECIMAL(6,4) NOT NULL DEFAULT 0.1144;
ALTER TABLE "valores_uf_utm" ADD COLUMN "afpHabitat"   DECIMAL(6,4) NOT NULL DEFAULT 0.1127;
ALTER TABLE "valores_uf_utm" ADD COLUMN "afpPlanvital" DECIMAL(6,4) NOT NULL DEFAULT 0.1127;
ALTER TABLE "valores_uf_utm" ADD COLUMN "afpProvida"   DECIMAL(6,4) NOT NULL DEFAULT 0.1145;
ALTER TABLE "valores_uf_utm" ADD COLUMN "afpModelo"    DECIMAL(6,4) NOT NULL DEFAULT 0.1077;
ALTER TABLE "valores_uf_utm" ADD COLUMN "afpUno"       DECIMAL(6,4) NOT NULL DEFAULT 0.1049;
