export const REGIONES_DT = [
  { codigo: '1', nombre: 'Tarapacá' },
  { codigo: '2', nombre: 'Antofagasta' },
  { codigo: '3', nombre: 'Atacama' },
  { codigo: '4', nombre: 'Coquimbo' },
  { codigo: '5', nombre: 'Valparaíso' },
  { codigo: '6', nombre: "O'Higgins" },
  { codigo: '7', nombre: 'Maule' },
  { codigo: '8', nombre: 'Biobío' },
  { codigo: '9', nombre: 'Araucanía' },
  { codigo: '10', nombre: 'Los Lagos' },
  { codigo: '11', nombre: 'Aysén' },
  { codigo: '12', nombre: 'Magallanes' },
  { codigo: '13', nombre: 'Metropolitana' },
  { codigo: '14', nombre: 'Los Ríos' },
  { codigo: '15', nombre: 'Arica y Parinacota' },
  { codigo: '16', nombre: 'Ñuble' },
] as const;

export const COMUNAS_DT: { codigo: string; nombre: string; region: string }[] = [
  // Region 1 - Tarapacá
  { codigo: '1101', nombre: 'Iquique', region: '1' },
  { codigo: '1102', nombre: 'Camiña', region: '1' },
  { codigo: '1103', nombre: 'Colchane', region: '1' },
  { codigo: '1104', nombre: 'Huara', region: '1' },
  { codigo: '1105', nombre: 'Pica', region: '1' },
  { codigo: '1106', nombre: 'Pozo Almonte', region: '1' },
  { codigo: '1107', nombre: 'Alto Hospicio', region: '1' },
  // Region 2 - Antofagasta
  { codigo: '2101', nombre: 'Antofagasta', region: '2' },
  { codigo: '2102', nombre: 'Mejillones', region: '2' },
  { codigo: '2103', nombre: 'Sierra Gorda', region: '2' },
  { codigo: '2104', nombre: 'Taltal', region: '2' },
  { codigo: '2105', nombre: 'María Elena', region: '2' },
  { codigo: '2201', nombre: 'Calama', region: '2' },
  { codigo: '2202', nombre: 'Ollagüe', region: '2' },
  { codigo: '2203', nombre: 'San Pedro de Atacama', region: '2' },
  { codigo: '2301', nombre: 'Tocopilla', region: '2' },
  // Region 3 - Atacama
  { codigo: '3101', nombre: 'Copiapó', region: '3' },
  { codigo: '3102', nombre: 'Caldera', region: '3' },
  { codigo: '3103', nombre: 'Tierra Amarilla', region: '3' },
  { codigo: '3201', nombre: 'Chañaral', region: '3' },
  { codigo: '3202', nombre: 'Diego de Almagro', region: '3' },
  { codigo: '3203', nombre: 'El Salvador', region: '3' },
  { codigo: '3301', nombre: 'Vallenar', region: '3' },
  { codigo: '3302', nombre: 'Alto del Carmen', region: '3' },
  { codigo: '3303', nombre: 'Freirina', region: '3' },
  { codigo: '3304', nombre: 'Huasco', region: '3' },
  // Region 4 - Coquimbo
  { codigo: '4101', nombre: 'La Serena', region: '4' },
  { codigo: '4102', nombre: 'Coquimbo', region: '4' },
  { codigo: '4103', nombre: 'Andacollo', region: '4' },
  { codigo: '4104', nombre: 'La Higuera', region: '4' },
  { codigo: '4105', nombre: 'Paihuano', region: '4' },
  { codigo: '4106', nombre: 'Vicuña', region: '4' },
  { codigo: '4201', nombre: 'Illapel', region: '4' },
  { codigo: '4202', nombre: 'Canela', region: '4' },
  { codigo: '4203', nombre: 'Los Vilos', region: '4' },
  { codigo: '4204', nombre: 'Salamanca', region: '4' },
  { codigo: '4301', nombre: 'Ovalle', region: '4' },
  { codigo: '4302', nombre: 'Combarbalá', region: '4' },
  { codigo: '4303', nombre: 'Monte Patria', region: '4' },
  { codigo: '4304', nombre: 'Punitaqui', region: '4' },
  { codigo: '4305', nombre: 'Río Hurtado', region: '4' },
  // Region 5 - Valparaíso
  { codigo: '5101', nombre: 'Valparaíso', region: '5' },
  { codigo: '5102', nombre: 'Casablanca', region: '5' },
  { codigo: '5103', nombre: 'Concón', region: '5' },
  { codigo: '5104', nombre: 'Juan Fernández', region: '5' },
  { codigo: '5105', nombre: 'Puchuncaví', region: '5' },
  { codigo: '5106', nombre: 'Quilpué', region: '5' },
  { codigo: '5107', nombre: 'Quintero', region: '5' },
  { codigo: '5108', nombre: 'Villa Alemana', region: '5' },
  { codigo: '5109', nombre: 'Viña del Mar', region: '5' },
  { codigo: '5201', nombre: 'Isla de Pascua', region: '5' },
  { codigo: '5301', nombre: 'Los Andes', region: '5' },
  { codigo: '5302', nombre: 'Calle Larga', region: '5' },
  { codigo: '5303', nombre: 'Rinconada', region: '5' },
  { codigo: '5304', nombre: 'San Esteban', region: '5' },
  { codigo: '5401', nombre: 'La Ligua', region: '5' },
  { codigo: '5402', nombre: 'Cabildo', region: '5' },
  { codigo: '5403', nombre: 'Papudo', region: '5' },
  { codigo: '5404', nombre: 'Petorca', region: '5' },
  { codigo: '5405', nombre: 'Zapallar', region: '5' },
  { codigo: '5501', nombre: 'Quillota', region: '5' },
  { codigo: '5502', nombre: 'La Calera', region: '5' },
  { codigo: '5503', nombre: 'Hijuelas', region: '5' },
  { codigo: '5504', nombre: 'La Cruz', region: '5' },
  { codigo: '5505', nombre: 'Limache', region: '5' },
  { codigo: '5506', nombre: 'Nogales', region: '5' },
  { codigo: '5507', nombre: 'Olmué', region: '5' },
  { codigo: '5601', nombre: 'San Antonio', region: '5' },
  { codigo: '5602', nombre: 'Algarrobo', region: '5' },
  { codigo: '5603', nombre: 'Cartagena', region: '5' },
  { codigo: '5604', nombre: 'El Quisco', region: '5' },
  { codigo: '5605', nombre: 'El Tabo', region: '5' },
  { codigo: '5606', nombre: 'Santo Domingo', region: '5' },
  { codigo: '5701', nombre: 'San Felipe', region: '5' },
  { codigo: '5702', nombre: 'Catemu', region: '5' },
  { codigo: '5703', nombre: 'Llay Llay', region: '5' },
  { codigo: '5704', nombre: 'Panquehue', region: '5' },
  { codigo: '5705', nombre: 'Putaendo', region: '5' },
  { codigo: '5706', nombre: 'Santa María', region: '5' },
  // Region 6 - O'Higgins
  { codigo: '6101', nombre: 'Rancagua', region: '6' },
  { codigo: '6102', nombre: 'Codegua', region: '6' },
  { codigo: '6103', nombre: 'Coinco', region: '6' },
  { codigo: '6104', nombre: 'Coltauco', region: '6' },
  { codigo: '6105', nombre: 'Doñihue', region: '6' },
  { codigo: '6106', nombre: 'Graneros', region: '6' },
  { codigo: '6107', nombre: 'Las Cabras', region: '6' },
  { codigo: '6108', nombre: 'Machalí', region: '6' },
  { codigo: '6109', nombre: 'Malloa', region: '6' },
  { codigo: '6110', nombre: 'Mostazal', region: '6' },
  { codigo: '6111', nombre: 'Olivar', region: '6' },
  { codigo: '6112', nombre: 'Peumo', region: '6' },
  { codigo: '6113', nombre: 'Pichidegua', region: '6' },
  { codigo: '6114', nombre: 'Quinta de Tilcoco', region: '6' },
  { codigo: '6115', nombre: 'Rengo', region: '6' },
  { codigo: '6116', nombre: 'Requínoa', region: '6' },
  { codigo: '6117', nombre: 'San Vicente', region: '6' },
  { codigo: '6201', nombre: 'Pichilemu', region: '6' },
  { codigo: '6202', nombre: 'La Estrella', region: '6' },
  { codigo: '6203', nombre: 'Litueche', region: '6' },
  { codigo: '6204', nombre: 'Marchigue', region: '6' },
  { codigo: '6205', nombre: 'Navidad', region: '6' },
  { codigo: '6206', nombre: 'Paredones', region: '6' },
  { codigo: '6301', nombre: 'San Fernando', region: '6' },
  { codigo: '6302', nombre: 'Chépica', region: '6' },
  { codigo: '6303', nombre: 'Chimbarongo', region: '6' },
  { codigo: '6304', nombre: 'Lolol', region: '6' },
  { codigo: '6305', nombre: 'Nancagua', region: '6' },
  { codigo: '6306', nombre: 'Palmilla', region: '6' },
  { codigo: '6307', nombre: 'Peralillo', region: '6' },
  { codigo: '6308', nombre: 'Placilla', region: '6' },
  { codigo: '6309', nombre: 'Pumanque', region: '6' },
  { codigo: '6310', nombre: 'Santa Cruz', region: '6' },
  // Region 7 - Maule
  { codigo: '7101', nombre: 'Talca', region: '7' },
  { codigo: '7102', nombre: 'Constitución', region: '7' },
  { codigo: '7103', nombre: 'Curepto', region: '7' },
  { codigo: '7104', nombre: 'Empedrado', region: '7' },
  { codigo: '7105', nombre: 'Maule', region: '7' },
  { codigo: '7106', nombre: 'Pelarco', region: '7' },
  { codigo: '7107', nombre: 'Pencahue', region: '7' },
  { codigo: '7108', nombre: 'Río Claro', region: '7' },
  { codigo: '7109', nombre: 'San Clemente', region: '7' },
  { codigo: '7110', nombre: 'San Rafael', region: '7' },
  { codigo: '7201', nombre: 'Cauquenes', region: '7' },
  { codigo: '7202', nombre: 'Chanco', region: '7' },
  { codigo: '7203', nombre: 'Pelluhue', region: '7' },
  { codigo: '7301', nombre: 'Curicó', region: '7' },
  { codigo: '7302', nombre: 'Hualañé', region: '7' },
  { codigo: '7303', nombre: 'Licantén', region: '7' },
  { codigo: '7304', nombre: 'Molina', region: '7' },
  { codigo: '7305', nombre: 'Rauco', region: '7' },
  { codigo: '7306', nombre: 'Romeral', region: '7' },
  { codigo: '7307', nombre: 'Sagrada Familia', region: '7' },
  { codigo: '7308', nombre: 'Teno', region: '7' },
  { codigo: '7309', nombre: 'Vichuquén', region: '7' },
  { codigo: '7401', nombre: 'Linares', region: '7' },
  { codigo: '7402', nombre: 'Colbún', region: '7' },
  { codigo: '7403', nombre: 'Longaví', region: '7' },
  { codigo: '7404', nombre: 'Parral', region: '7' },
  { codigo: '7405', nombre: 'Retiro', region: '7' },
  { codigo: '7406', nombre: 'San Javier', region: '7' },
  { codigo: '7407', nombre: 'Villa Alegre', region: '7' },
  { codigo: '7408', nombre: 'Yerbas Buenas', region: '7' },
  // Region 8 - Biobío
  { codigo: '8101', nombre: 'Concepción', region: '8' },
  { codigo: '8102', nombre: 'Coronel', region: '8' },
  { codigo: '8103', nombre: 'Chiguayante', region: '8' },
  { codigo: '8104', nombre: 'Florida', region: '8' },
  { codigo: '8105', nombre: 'Hualqui', region: '8' },
  { codigo: '8106', nombre: 'Lota', region: '8' },
  { codigo: '8107', nombre: 'Penco', region: '8' },
  { codigo: '8108', nombre: 'San Pedro de la Paz', region: '8' },
  { codigo: '8109', nombre: 'Santa Juana', region: '8' },
  { codigo: '8110', nombre: 'Talcahuano', region: '8' },
  { codigo: '8111', nombre: 'Tomé', region: '8' },
  { codigo: '8112', nombre: 'Hualpén', region: '8' },
  { codigo: '8201', nombre: 'Lebu', region: '8' },
  { codigo: '8202', nombre: 'Arauco', region: '8' },
  { codigo: '8203', nombre: 'Cañete', region: '8' },
  { codigo: '8204', nombre: 'Contulmo', region: '8' },
  { codigo: '8205', nombre: 'Curanilahue', region: '8' },
  { codigo: '8206', nombre: 'Los Álamos', region: '8' },
  { codigo: '8207', nombre: 'Tirúa', region: '8' },
  { codigo: '8301', nombre: 'Los Ángeles', region: '8' },
  { codigo: '8302', nombre: 'Antuco', region: '8' },
  { codigo: '8303', nombre: 'Cabrero', region: '8' },
  { codigo: '8304', nombre: 'Laja', region: '8' },
  { codigo: '8305', nombre: 'Mulchén', region: '8' },
  { codigo: '8306', nombre: 'Nacimiento', region: '8' },
  { codigo: '8307', nombre: 'Negrete', region: '8' },
  { codigo: '8308', nombre: 'Quilaco', region: '8' },
  { codigo: '8309', nombre: 'Quilleco', region: '8' },
  { codigo: '8310', nombre: 'San Rosendo', region: '8' },
  { codigo: '8311', nombre: 'Santa Bárbara', region: '8' },
  { codigo: '8312', nombre: 'Tucapel', region: '8' },
  { codigo: '8313', nombre: 'Yumbel', region: '8' },
  { codigo: '8314', nombre: 'Alto Biobío', region: '8' },
  // Region 9 - Araucanía
  { codigo: '9101', nombre: 'Temuco', region: '9' },
  { codigo: '9102', nombre: 'Carahue', region: '9' },
  { codigo: '9103', nombre: 'Cunco', region: '9' },
  { codigo: '9104', nombre: 'Curarrehue', region: '9' },
  { codigo: '9105', nombre: 'Freire', region: '9' },
  { codigo: '9106', nombre: 'Galvarino', region: '9' },
  { codigo: '9107', nombre: 'Gorbea', region: '9' },
  { codigo: '9108', nombre: 'Lautaro', region: '9' },
  { codigo: '9109', nombre: 'Loncoche', region: '9' },
  { codigo: '9110', nombre: 'Melipeuco', region: '9' },
  { codigo: '9111', nombre: 'Nueva Imperial', region: '9' },
  { codigo: '9112', nombre: 'Padre Las Casas', region: '9' },
  { codigo: '9113', nombre: 'Perquenco', region: '9' },
  { codigo: '9114', nombre: 'Pitrufquén', region: '9' },
  { codigo: '9115', nombre: 'Pucón', region: '9' },
  { codigo: '9116', nombre: 'Saavedra', region: '9' },
  { codigo: '9117', nombre: 'Teodoro Schmidt', region: '9' },
  { codigo: '9118', nombre: 'Toltén', region: '9' },
  { codigo: '9119', nombre: 'Vilcún', region: '9' },
  { codigo: '9120', nombre: 'Villarrica', region: '9' },
  { codigo: '9121', nombre: 'Cholchol', region: '9' },
  { codigo: '9201', nombre: 'Angol', region: '9' },
  { codigo: '9202', nombre: 'Collipulli', region: '9' },
  { codigo: '9203', nombre: 'Curacautín', region: '9' },
  { codigo: '9204', nombre: 'Ercilla', region: '9' },
  { codigo: '9205', nombre: 'Lonquimay', region: '9' },
  { codigo: '9206', nombre: 'Los Sauces', region: '9' },
  { codigo: '9207', nombre: 'Lumaco', region: '9' },
  { codigo: '9208', nombre: 'Purén', region: '9' },
  { codigo: '9209', nombre: 'Renaico', region: '9' },
  { codigo: '9210', nombre: 'Traiguén', region: '9' },
  { codigo: '9211', nombre: 'Victoria', region: '9' },
  // Region 10 - Los Lagos
  { codigo: '10101', nombre: 'Puerto Montt', region: '10' },
  { codigo: '10102', nombre: 'Calbuco', region: '10' },
  { codigo: '10103', nombre: 'Cochamó', region: '10' },
  { codigo: '10104', nombre: 'Fresia', region: '10' },
  { codigo: '10105', nombre: 'Frutillar', region: '10' },
  { codigo: '10106', nombre: 'Los Muermos', region: '10' },
  { codigo: '10107', nombre: 'Llanquihue', region: '10' },
  { codigo: '10108', nombre: 'Maullín', region: '10' },
  { codigo: '10109', nombre: 'Puerto Varas', region: '10' },
  { codigo: '10201', nombre: 'Castro', region: '10' },
  { codigo: '10202', nombre: 'Ancud', region: '10' },
  { codigo: '10203', nombre: 'Chonchi', region: '10' },
  { codigo: '10204', nombre: 'Curaco de Vélez', region: '10' },
  { codigo: '10205', nombre: 'Dalcahue', region: '10' },
  { codigo: '10206', nombre: 'Puqueldón', region: '10' },
  { codigo: '10207', nombre: 'Queilén', region: '10' },
  { codigo: '10208', nombre: 'Quellón', region: '10' },
  { codigo: '10209', nombre: 'Quemchi', region: '10' },
  { codigo: '10210', nombre: 'Quinchao', region: '10' },
  { codigo: '10301', nombre: 'Osorno', region: '10' },
  { codigo: '10302', nombre: 'Puerto Octay', region: '10' },
  { codigo: '10303', nombre: 'Purranque', region: '10' },
  { codigo: '10304', nombre: 'Puyehue', region: '10' },
  { codigo: '10305', nombre: 'Río Negro', region: '10' },
  { codigo: '10306', nombre: 'San Juan de la Costa', region: '10' },
  { codigo: '10307', nombre: 'San Pablo', region: '10' },
  { codigo: '10401', nombre: 'Chaitén', region: '10' },
  { codigo: '10402', nombre: 'Futaleufú', region: '10' },
  { codigo: '10403', nombre: 'Hualaihué', region: '10' },
  { codigo: '10404', nombre: 'Palena', region: '10' },
  // Region 11 - Aysén
  { codigo: '11101', nombre: 'Coihaique', region: '11' },
  { codigo: '11102', nombre: 'Lago Verde', region: '11' },
  { codigo: '11201', nombre: 'Aisén', region: '11' },
  { codigo: '11202', nombre: 'Cisnes', region: '11' },
  { codigo: '11203', nombre: 'Guaitecas', region: '11' },
  { codigo: '11301', nombre: 'Cochrane', region: '11' },
  { codigo: '11302', nombre: "O'Higgins", region: '11' },
  { codigo: '11303', nombre: 'Tortel', region: '11' },
  { codigo: '11401', nombre: 'Chile Chico', region: '11' },
  { codigo: '11402', nombre: 'Río Ibáñez', region: '11' },
  // Region 12 - Magallanes
  { codigo: '12101', nombre: 'Punta Arenas', region: '12' },
  { codigo: '12102', nombre: 'Laguna Blanca', region: '12' },
  { codigo: '12103', nombre: 'Río Verde', region: '12' },
  { codigo: '12104', nombre: 'San Gregorio', region: '12' },
  { codigo: '12201', nombre: 'Cabo de Hornos', region: '12' },
  { codigo: '12202', nombre: 'Antártica', region: '12' },
  { codigo: '12301', nombre: 'Porvenir', region: '12' },
  { codigo: '12302', nombre: 'Primavera', region: '12' },
  { codigo: '12303', nombre: 'Timaukel', region: '12' },
  { codigo: '12401', nombre: 'Natales', region: '12' },
  { codigo: '12402', nombre: 'Torres del Paine', region: '12' },
  // Region 13 - Metropolitana
  { codigo: '13101', nombre: 'Santiago', region: '13' },
  { codigo: '13102', nombre: 'Cerrillos', region: '13' },
  { codigo: '13103', nombre: 'Cerro Navia', region: '13' },
  { codigo: '13104', nombre: 'Conchalí', region: '13' },
  { codigo: '13105', nombre: 'El Bosque', region: '13' },
  { codigo: '13106', nombre: 'Estación Central', region: '13' },
  { codigo: '13107', nombre: 'Huechuraba', region: '13' },
  { codigo: '13108', nombre: 'Independencia', region: '13' },
  { codigo: '13109', nombre: 'La Cisterna', region: '13' },
  { codigo: '13110', nombre: 'La Florida', region: '13' },
  { codigo: '13111', nombre: 'La Granja', region: '13' },
  { codigo: '13112', nombre: 'La Pintana', region: '13' },
  { codigo: '13113', nombre: 'La Reina', region: '13' },
  { codigo: '13114', nombre: 'Las Condes', region: '13' },
  { codigo: '13115', nombre: 'Lo Barnechea', region: '13' },
  { codigo: '13116', nombre: 'Lo Espejo', region: '13' },
  { codigo: '13117', nombre: 'Lo Prado', region: '13' },
  { codigo: '13118', nombre: 'Macul', region: '13' },
  { codigo: '13119', nombre: 'Maipú', region: '13' },
  { codigo: '13120', nombre: 'Ñuñoa', region: '13' },
  { codigo: '13121', nombre: 'Pedro Aguirre Cerda', region: '13' },
  { codigo: '13122', nombre: 'Peñalolén', region: '13' },
  { codigo: '13123', nombre: 'Providencia', region: '13' },
  { codigo: '13124', nombre: 'Pudahuel', region: '13' },
  { codigo: '13125', nombre: 'Quilicura', region: '13' },
  { codigo: '13126', nombre: 'Quinta Normal', region: '13' },
  { codigo: '13127', nombre: 'Recoleta', region: '13' },
  { codigo: '13128', nombre: 'Renca', region: '13' },
  { codigo: '13129', nombre: 'San Joaquín', region: '13' },
  { codigo: '13130', nombre: 'San Miguel', region: '13' },
  { codigo: '13131', nombre: 'San Ramón', region: '13' },
  { codigo: '13132', nombre: 'Vitacura', region: '13' },
  { codigo: '13201', nombre: 'Puente Alto', region: '13' },
  { codigo: '13202', nombre: 'Pirque', region: '13' },
  { codigo: '13203', nombre: 'San José de Maipo', region: '13' },
  { codigo: '13301', nombre: 'Colina', region: '13' },
  { codigo: '13302', nombre: 'Lampa', region: '13' },
  { codigo: '13303', nombre: 'Tiltil', region: '13' },
  { codigo: '13401', nombre: 'San Bernardo', region: '13' },
  { codigo: '13402', nombre: 'Buin', region: '13' },
  { codigo: '13403', nombre: 'Calera de Tango', region: '13' },
  { codigo: '13404', nombre: 'Paine', region: '13' },
  { codigo: '13501', nombre: 'Melipilla', region: '13' },
  { codigo: '13502', nombre: 'Alhué', region: '13' },
  { codigo: '13503', nombre: 'Curacaví', region: '13' },
  { codigo: '13504', nombre: 'María Pinto', region: '13' },
  { codigo: '13505', nombre: 'San Pedro', region: '13' },
  { codigo: '13601', nombre: 'Talagante', region: '13' },
  { codigo: '13602', nombre: 'El Monte', region: '13' },
  { codigo: '13603', nombre: 'Isla de Maipo', region: '13' },
  { codigo: '13604', nombre: 'Padre Hurtado', region: '13' },
  { codigo: '13605', nombre: 'Peñaflor', region: '13' },
  // Region 14 - Los Ríos
  { codigo: '14101', nombre: 'Valdivia', region: '14' },
  { codigo: '14102', nombre: 'Corral', region: '14' },
  { codigo: '14103', nombre: 'Futrono', region: '14' },
  { codigo: '14104', nombre: 'La Unión', region: '14' },
  { codigo: '14105', nombre: 'Lago Ranco', region: '14' },
  { codigo: '14106', nombre: 'Lanco', region: '14' },
  { codigo: '14107', nombre: 'Los Lagos', region: '14' },
  { codigo: '14108', nombre: 'Máfil', region: '14' },
  { codigo: '14109', nombre: 'Mariquina', region: '14' },
  { codigo: '14110', nombre: 'Paillaco', region: '14' },
  { codigo: '14111', nombre: 'Panguipulli', region: '14' },
  { codigo: '14112', nombre: 'Río Bueno', region: '14' },
  // Region 15 - Arica y Parinacota
  { codigo: '15101', nombre: 'Arica', region: '15' },
  { codigo: '15102', nombre: 'Camarones', region: '15' },
  { codigo: '15201', nombre: 'Putre', region: '15' },
  { codigo: '15202', nombre: 'General Lagos', region: '15' },
  // Region 16 - Ñuble
  { codigo: '8401', nombre: 'Chillán', region: '16' },
  { codigo: '8402', nombre: 'Bulnes', region: '16' },
  { codigo: '8403', nombre: 'Cobquecura', region: '16' },
  { codigo: '8404', nombre: 'Coelemu', region: '16' },
  { codigo: '8405', nombre: 'Coihueco', region: '16' },
  { codigo: '8406', nombre: 'Chillán Viejo', region: '16' },
  { codigo: '8407', nombre: 'El Carmen', region: '16' },
  { codigo: '8408', nombre: 'Ninhue', region: '16' },
  { codigo: '8409', nombre: 'Ñiquén', region: '16' },
  { codigo: '8410', nombre: 'Pemuco', region: '16' },
  { codigo: '8411', nombre: 'Pinto', region: '16' },
  { codigo: '8412', nombre: 'Portezuelo', region: '16' },
  { codigo: '8413', nombre: 'Quillón', region: '16' },
  { codigo: '8414', nombre: 'Quirihue', region: '16' },
  { codigo: '8415', nombre: 'Ránquil', region: '16' },
  { codigo: '8416', nombre: 'San Carlos', region: '16' },
  { codigo: '8417', nombre: 'San Fabián', region: '16' },
  { codigo: '8418', nombre: 'San Ignacio', region: '16' },
  { codigo: '8419', nombre: 'San Nicolás', region: '16' },
  { codigo: '8420', nombre: 'Treguaco', region: '16' },
  { codigo: '8421', nombre: 'Yungay', region: '16' },
];
